import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { setRequestLocale } from 'next-intl/server';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import { DEFAULT_LOCALE } from '@/config';
import Footer from '@/components/Footer/Footer';
import ButtonGoTop from '@/components/ButtonGotop/ButtonGoTop';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({ children, params }: any) {
  const locale = params.locale || DEFAULT_LOCALE;

  if (!locale || !hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <NextIntlClientProvider locale={locale}>
        <body className={`antialiased`}>
          <Header />
          <main>{children}</main>
          <Footer />
          <ButtonGoTop />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
